services:
  - type: web
    name: bridge-africa-app
    runtime: docker  
    plan: free       
    dockerfilePath: ./Dockerfile
    buildCommand: "" 
    startCommand: "" 
    envVars:
      - key: APP_KEY
        value: base64:R2YCKFG5DwM7SriPBSuWzzuJiOvYUMB9cKNELvq12AU=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: bridge_africa
      - key: DB_USERNAME
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
